//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.WSTecnologicoATS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_importacion_ats_fixed", Namespace="http://schemas.datacontract.org/2004/07/WsSegaEcErp.Models")]
    [System.SerializableAttribute()]
    public partial class vw_importacion_ats_fixed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoObjIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUC_LCGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int baseImpGravField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cedulaRucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fe_facturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nu_compField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> valorBaseIvaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoObjIva {
            get {
                return this.NoObjIvaField;
            }
            set {
                if ((this.NoObjIvaField.Equals(value) != true)) {
                    this.NoObjIvaField = value;
                    this.RaisePropertyChanged("NoObjIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC_LCG {
            get {
                return this.RUC_LCGField;
            }
            set {
                if ((object.ReferenceEquals(this.RUC_LCGField, value) != true)) {
                    this.RUC_LCGField = value;
                    this.RaisePropertyChanged("RUC_LCG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int baseImpGrav {
            get {
                return this.baseImpGravField;
            }
            set {
                if ((this.baseImpGravField.Equals(value) != true)) {
                    this.baseImpGravField = value;
                    this.RaisePropertyChanged("baseImpGrav");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cedulaRuc {
            get {
                return this.cedulaRucField;
            }
            set {
                if ((object.ReferenceEquals(this.cedulaRucField, value) != true)) {
                    this.cedulaRucField = value;
                    this.RaisePropertyChanged("cedulaRuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fe_factura {
            get {
                return this.fe_facturaField;
            }
            set {
                if ((this.fe_facturaField.Equals(value) != true)) {
                    this.fe_facturaField = value;
                    this.RaisePropertyChanged("fe_factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nu_comp {
            get {
                return this.nu_compField;
            }
            set {
                if ((this.nu_compField.Equals(value) != true)) {
                    this.nu_compField = value;
                    this.RaisePropertyChanged("nu_comp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> valorBaseIva {
            get {
                return this.valorBaseIvaField;
            }
            set {
                if ((this.valorBaseIvaField.Equals(value) != true)) {
                    this.valorBaseIvaField = value;
                    this.RaisePropertyChanged("valorBaseIva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTecnologicoATS.IWsSegaEcErp")]
    public interface IWsSegaEcErp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsSegaEcErp/vw_importacion_ats_fixed", ReplyAction="http://tempuri.org/IWsSegaEcErp/vw_importacion_ats_fixedResponse")]
        Core.Erp.Data.WSTecnologicoATS.vw_importacion_ats_fixed[] vw_importacion_ats_fixed(int id_empre, System.DateTime _fe_desde, System.DateTime _fe_hasta, string _user, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsSegaEcErp/vw_importacion_ats_fixed", ReplyAction="http://tempuri.org/IWsSegaEcErp/vw_importacion_ats_fixedResponse")]
        System.Threading.Tasks.Task<Core.Erp.Data.WSTecnologicoATS.vw_importacion_ats_fixed[]> vw_importacion_ats_fixedAsync(int id_empre, System.DateTime _fe_desde, System.DateTime _fe_hasta, string _user, string _password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsSegaEcErpChannel : Core.Erp.Data.WSTecnologicoATS.IWsSegaEcErp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsSegaEcErpClient : System.ServiceModel.ClientBase<Core.Erp.Data.WSTecnologicoATS.IWsSegaEcErp>, Core.Erp.Data.WSTecnologicoATS.IWsSegaEcErp {
        
        public WsSegaEcErpClient() {
        }
        
        public WsSegaEcErpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsSegaEcErpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSegaEcErpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSegaEcErpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Core.Erp.Data.WSTecnologicoATS.vw_importacion_ats_fixed[] vw_importacion_ats_fixed(int id_empre, System.DateTime _fe_desde, System.DateTime _fe_hasta, string _user, string _password) {
            return base.Channel.vw_importacion_ats_fixed(id_empre, _fe_desde, _fe_hasta, _user, _password);
        }
        
        public System.Threading.Tasks.Task<Core.Erp.Data.WSTecnologicoATS.vw_importacion_ats_fixed[]> vw_importacion_ats_fixedAsync(int id_empre, System.DateTime _fe_desde, System.DateTime _fe_hasta, string _user, string _password) {
            return base.Channel.vw_importacion_ats_fixedAsync(id_empre, _fe_desde, _fe_hasta, _user, _password);
        }
    }
}
