//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.WSTecnologicoATS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTecnologicoATS.IWsTecno")]
    public interface IWsTecno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTecno/CreateCliente", ReplyAction="http://tempuri.org/IWsTecno/CreateClienteResponse")]
        int CreateCliente(string tx_nombre, string ced_ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTecno/CreateCliente", ReplyAction="http://tempuri.org/IWsTecno/CreateClienteResponse")]
        System.Threading.Tasks.Task<int> CreateClienteAsync(string tx_nombre, string ced_ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTecno/CreateDocumento", ReplyAction="http://tempuri.org/IWsTecno/CreateDocumentoResponse")]
        bool CreateDocumento(int _tipoDoc, int _id_cliente, string _clave, string nu_doc, string tx_nombre, string ced_ruc, System.DateTime fe_autorizacion, string nu_autorizacion, string nu_docsustento, string tx_xml, double _total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTecno/CreateDocumento", ReplyAction="http://tempuri.org/IWsTecno/CreateDocumentoResponse")]
        System.Threading.Tasks.Task<bool> CreateDocumentoAsync(int _tipoDoc, int _id_cliente, string _clave, string nu_doc, string tx_nombre, string ced_ruc, System.DateTime fe_autorizacion, string nu_autorizacion, string nu_docsustento, string tx_xml, double _total);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsTecnoChannel : Core.Erp.Data.WSTecnologicoATS.IWsTecno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsTecnoClient : System.ServiceModel.ClientBase<Core.Erp.Data.WSTecnologicoATS.IWsTecno>, Core.Erp.Data.WSTecnologicoATS.IWsTecno {
        
        public WsTecnoClient() {
        }
        
        public WsTecnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsTecnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsTecnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsTecnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateCliente(string tx_nombre, string ced_ruc) {
            return base.Channel.CreateCliente(tx_nombre, ced_ruc);
        }
        
        public System.Threading.Tasks.Task<int> CreateClienteAsync(string tx_nombre, string ced_ruc) {
            return base.Channel.CreateClienteAsync(tx_nombre, ced_ruc);
        }
        
        public bool CreateDocumento(int _tipoDoc, int _id_cliente, string _clave, string nu_doc, string tx_nombre, string ced_ruc, System.DateTime fe_autorizacion, string nu_autorizacion, string nu_docsustento, string tx_xml, double _total) {
            return base.Channel.CreateDocumento(_tipoDoc, _id_cliente, _clave, nu_doc, tx_nombre, ced_ruc, fe_autorizacion, nu_autorizacion, nu_docsustento, tx_xml, _total);
        }
        
        public System.Threading.Tasks.Task<bool> CreateDocumentoAsync(int _tipoDoc, int _id_cliente, string _clave, string nu_doc, string tx_nombre, string ced_ruc, System.DateTime fe_autorizacion, string nu_autorizacion, string nu_docsustento, string tx_xml, double _total) {
            return base.Channel.CreateDocumentoAsync(_tipoDoc, _id_cliente, _clave, nu_doc, tx_nombre, ced_ruc, fe_autorizacion, nu_autorizacion, nu_docsustento, tx_xml, _total);
        }
    }
}
