CREATE TABLE [dbo].[aca_Admision] (
    [IdEmpresa]                            INT           NOT NULL,
    [IdAdmision]                           DECIMAL (18)  NOT NULL,
    [IdSede]                               INT           NOT NULL,
    [IdAnio]                               INT           NOT NULL,
    [IdJornada]                            INT           NOT NULL,
    [IdNivel]                              INT           NOT NULL,
    [IdCurso]                              INT           NOT NULL,
    [Naturaleza_Aspirante]                 VARCHAR (25)  NOT NULL,
    [IdTipoDocumento_Aspirante]            VARCHAR (25)  NOT NULL,
    [CedulaRuc_Aspirante]                  VARCHAR (50)  NOT NULL,
    [Nombres_Aspirante]                    VARCHAR (100) NULL,
    [Apellidos_Aspirante]                  VARCHAR (100) NULL,
    [NombreCompleto_Aspirante]             VARCHAR (200) NOT NULL,
    [Direccion_Aspirante]                  VARCHAR (150) NULL,
    [Telefono_Aspirante]                   VARCHAR (50)  NULL,
    [Celular_Aspirante]                    VARCHAR (50)  NULL,
    [Correo_Aspirante]                     VARCHAR (100) NULL,
    [Sexo_Aspirante]                       VARCHAR (25)  NULL,
    [FechaNacimiento_Aspirante]            DATETIME      NULL,
    [CodCatalogoSangre_Aspirante]          VARCHAR (25)  NULL,
    [CodCatalogoCONADIS_Aspirante]         VARCHAR (25)  NULL,
    [PorcentajeDiscapacidad_Aspirante]     FLOAT (53)    NULL,
    [NumeroCarnetConadis_Aspirante]        VARCHAR (200) NULL,
    [IdGrupoEtnico_Aspirante]              INT           NULL,
    [IdReligion_Aspirante]                 INT           NULL,
    [AsisteCentroCristiano_Aspirante]      BIT           NULL,
    [LugarNacimiento_Aspirante]            VARCHAR (300) NULL,
    [IdPais_Aspirante]                     VARCHAR (10)  NULL,
    [Cod_Region_Aspirante]                 VARCHAR (10)  NULL,
    [IdProvincia_Aspirante]                VARCHAR (25)  NULL,
    [IdCiudad_Aspirante]                   VARCHAR (25)  NULL,
    [IdParroquia_Aspirante]                VARCHAR (25)  NULL,
    [Sector_Aspirante]                     VARCHAR (500) NULL,
    [FechaIngreso_Aspirante]               DATE          NOT NULL,
    [IdCatalogoFichaTipoViv_Aspirante]     INT           NOT NULL,
    [IdCatalogoFichaViv_Aspirante]         INT           NOT NULL,
    [IdCatalogoFichaAgua_Aspirante]        INT           NOT NULL,
    [TieneElectricidad_Aspirante]          BIT           NOT NULL,
    [TieneHermanos_Aspirante]              BIT           NOT NULL,
    [IdCatalogoFichaMotivo_Aspirante]      INT           NOT NULL,
    [IdCatalogoFichaInst_Aspirante]        INT           NOT NULL,
    [IdCatalogoFichaFinanc_Aspirante]      INT           NOT NULL,
    [IdCatalogoFichaVive_Aspirante]        INT           NOT NULL,
    [OtroMotivoIngreso_Aspirante]          VARCHAR (MAX) NULL,
    [OtroInformacionInst_Aspirante]        VARCHAR (MAX) NULL,
    [OtroFinanciamiento_Aspirante]         VARCHAR (MAX) NULL,
    [Naturaleza_Padre]                     VARCHAR (25)  NOT NULL,
    [IdTipoDocumento_Padre]                VARCHAR (25)  NOT NULL,
    [CedulaRuc_Padre]                      VARCHAR (50)  NOT NULL,
    [Nombres_Padre]                        VARCHAR (100) NULL,
    [Apellidos_Padre]                      VARCHAR (100) NULL,
    [NombreCompleto_Padre]                 VARCHAR (200) NOT NULL,
    [RazonSocial_Padre]                    VARCHAR (150) NULL,
    [Direccion_Padre]                      VARCHAR (150) NULL,
    [Telefono_Padre]                       VARCHAR (50)  NULL,
    [Celular_Padre]                        VARCHAR (50)  NULL,
    [Correo_Padre]                         VARCHAR (100) NULL,
    [Sexo_Padre]                           VARCHAR (25)  NULL,
    [FechaNacimiento_Padre]                DATETIME      NULL,
    [CodCatalogoSangre_Padre]              VARCHAR (25)  NULL,
    [CodCatalogoCONADIS_Padre]             VARCHAR (25)  NULL,
    [PorcentajeDiscapacidad_Padre]         FLOAT (53)    NULL,
    [NumeroCarnetConadis_Padre]            VARCHAR (200) NULL,
    [IdGrupoEtnico_Padre]                  INT           NULL,
    [IdReligion_Padre]                     INT           NULL,
    [IdEstadoCivil_Padre]                  VARCHAR (25)  NULL,
    [AsisteCentroCristiano_Padre]          BIT           NOT NULL,
    [IdPais_Padre]                         VARCHAR (10)  NULL,
    [Cod_Region_Padre]                     VARCHAR (10)  NULL,
    [IdProvincia_Padre]                    VARCHAR (25)  NULL,
    [IdCiudad_Padre]                       VARCHAR (25)  NULL,
    [IdParroquia_Padre]                    VARCHAR (25)  NULL,
    [Sector_Padre]                         VARCHAR (500) NULL,
    [IdCatalogoPAREN_Padre]                INT           NOT NULL,
    [IdCatalogoFichaInst_Padre]            INT           NULL,
    [EmpresaTrabajo_Padre]                 VARCHAR (200) NULL,
    [DireccionTrabajo_Padre]               VARCHAR (500) NULL,
    [TelefonoTrabajo_Padre]                VARCHAR (200) NULL,
    [CargoTrabajo_Padre]                   VARCHAR (200) NULL,
    [AniosServicio_Padre]                  INT           NULL,
    [IngresoMensual_Padre]                 FLOAT (53)    NULL,
    [VehiculoPropio_Padre]                 BIT           NOT NULL,
    [Marca_Padre]                          VARCHAR (50)  NULL,
    [Modelo_Padre]                         VARCHAR (50)  NULL,
    [AnioVehiculo_Padre]                   INT           NULL,
    [CasaPropia_Padre]                     BIT           NOT NULL,
    [EstaFallecido_Padre]                  BIT           NOT NULL,
    [Naturaleza_Madre]                     VARCHAR (25)  NOT NULL,
    [IdTipoDocumento_Madre]                VARCHAR (25)  NOT NULL,
    [CedulaRuc_Madre]                      VARCHAR (50)  NOT NULL,
    [Nombres_Madre]                        VARCHAR (100) NULL,
    [Apellidos_Madre]                      VARCHAR (100) NULL,
    [NombreCompleto_Madre]                 VARCHAR (200) NOT NULL,
    [RazonSocial_Madre]                    VARCHAR (150) NULL,
    [Direccion_Madre]                      VARCHAR (150) NULL,
    [Telefono_Madre]                       VARCHAR (50)  NULL,
    [Celular_Madre]                        VARCHAR (50)  NULL,
    [Correo_Madre]                         VARCHAR (100) NULL,
    [Sexo_Madre]                           VARCHAR (25)  NULL,
    [FechaNacimiento_Madre]                DATETIME      NULL,
    [CodCatalogoSangre_Madre]              VARCHAR (25)  NULL,
    [CodCatalogoCONADIS_Madre]             VARCHAR (25)  NULL,
    [PorcentajeDiscapacidad_Madre]         FLOAT (53)    NULL,
    [NumeroCarnetConadis_Madre]            VARCHAR (200) NULL,
    [IdGrupoEtnico_Madre]                  INT           NULL,
    [IdReligion_Madre]                     INT           NULL,
    [IdEstadoCivil_Madre]                  VARCHAR (25)  NULL,
    [AsisteCentroCristiano_Madre]          BIT           NOT NULL,
    [IdPais_Madre]                         VARCHAR (10)  NULL,
    [Cod_Region_Madre]                     VARCHAR (10)  NULL,
    [IdProvincia_Madre]                    VARCHAR (25)  NULL,
    [IdCiudad_Madre]                       VARCHAR (25)  NULL,
    [IdParroquia_Madre]                    VARCHAR (25)  NULL,
    [Sector_Madre]                         VARCHAR (500) NULL,
    [IdCatalogoPAREN_Madre]                INT           NOT NULL,
    [IdCatalogoFichaInst_Madre]            INT           NULL,
    [EmpresaTrabajo_Madre]                 VARCHAR (200) NULL,
    [DireccionTrabajo_Madre]               VARCHAR (500) NULL,
    [TelefonoTrabajo_Madre]                VARCHAR (200) NULL,
    [CargoTrabajo_Madre]                   VARCHAR (200) NULL,
    [AniosServicio_Madre]                  INT           NULL,
    [IngresoMensual_Madre]                 FLOAT (53)    NULL,
    [VehiculoPropio_Madre]                 BIT           NOT NULL,
    [Marca_Madre]                          VARCHAR (50)  NULL,
    [Modelo_Madre]                         VARCHAR (50)  NULL,
    [AnioVehiculo_Madre]                   INT           NULL,
    [CasaPropia_Madre]                     BIT           NOT NULL,
    [EstaFallecido_Madre]                  BIT           NOT NULL,
    [Naturaleza_Representante]             VARCHAR (25)  NOT NULL,
    [IdTipoDocumento_Representante]        VARCHAR (25)  NOT NULL,
    [CedulaRuc_Representante]              VARCHAR (50)  NOT NULL,
    [Nombres_Representante]                VARCHAR (100) NULL,
    [Apellidos_Representante]              VARCHAR (100) NULL,
    [NombreCompleto_Representante]         VARCHAR (200) NOT NULL,
    [RazonSocial_Representante]            VARCHAR (150) NULL,
    [Direccion_Representante]              VARCHAR (150) NULL,
    [Telefono_Representante]               VARCHAR (50)  NULL,
    [Celular_Representante]                VARCHAR (50)  NULL,
    [Correo_Representante]                 VARCHAR (100) NULL,
    [Sexo_Representante]                   VARCHAR (25)  NULL,
    [FechaNacimiento_Representante]        DATETIME      NULL,
    [CodCatalogoSangre_Representante]      VARCHAR (25)  NULL,
    [CodCatalogoCONADIS_Representante]     VARCHAR (25)  NULL,
    [PorcentajeDiscapacidad_Representante] FLOAT (53)    NULL,
    [NumeroCarnetConadis_Representante]    VARCHAR (200) NULL,
    [IdGrupoEtnico_Representante]          INT           NULL,
    [IdReligion_Representante]             INT           NULL,
    [IdEstadoCivil_Representante]          VARCHAR (25)  NULL,
    [AsisteCentroCristiano_Representante]  BIT           NOT NULL,
    [IdPais_Representante]                 VARCHAR (10)  NULL,
    [Cod_Region_Representante]             VARCHAR (10)  NULL,
    [IdProvincia_Representante]            VARCHAR (25)  NULL,
    [IdCiudad_Representante]               VARCHAR (25)  NULL,
    [IdParroquia_Representante]            VARCHAR (25)  NULL,
    [Sector_Representante]                 VARCHAR (500) NULL,
    [IdCatalogoPAREN_Representante]        INT           NOT NULL,
    [IdCatalogoFichaInst_Representante]    INT           NULL,
    [EmpresaTrabajo_Representante]         VARCHAR (200) NULL,
    [DireccionTrabajo_Representante]       VARCHAR (500) NULL,
    [TelefonoTrabajo_Representante]        VARCHAR (200) NULL,
    [CargoTrabajo_Representante]           VARCHAR (200) NULL,
    [AniosServicio_Representante]          INT           NULL,
    [IngresoMensual_Representante]         FLOAT (53)    NULL,
    [VehiculoPropio_Representante]         BIT           NOT NULL,
    [Marca_Representante]                  VARCHAR (50)  NULL,
    [Modelo_Representante]                 VARCHAR (50)  NULL,
    [AnioVehiculo_Representante]           INT           NULL,
    [CasaPropia_Representante]             BIT           NOT NULL,
    [EstaFallecido_Representante]          BIT           NOT NULL,
    [SueldoPadre]                          FLOAT (53)    NOT NULL,
    [SueldoMadre]                          FLOAT (53)    NOT NULL,
    [OtroIngresoPadre]                     FLOAT (53)    NOT NULL,
    [OtroIngresoMadre]                     FLOAT (53)    NOT NULL,
    [GastoAlimentacion]                    FLOAT (53)    NOT NULL,
    [GastoEducacion]                       FLOAT (53)    NOT NULL,
    [GastoServicioBasico]                  FLOAT (53)    NOT NULL,
    [GastoSalud]                           FLOAT (53)    NOT NULL,
    [GastoArriendo]                        FLOAT (53)    NOT NULL,
    [GastoPrestamo]                        FLOAT (53)    NOT NULL,
    [OtroGasto]                            FLOAT (53)    NOT NULL,
    [IdUsuarioCreacion]                    VARCHAR (200) NULL,
    [FechaCreacion]                        DATETIME      NULL,
    [IdUsuarioModificacion]                VARCHAR (200) NULL,
    [FechaModificacion]                    DATETIME      NULL,
    [IdUsuarioAnulacion]                   VARCHAR (200) NULL,
    [FechaAnulacion]                       DATETIME      NULL,
    [MotivoAnulacion]                      VARCHAR (MAX) NULL,
    CONSTRAINT [PK_aca_Admision] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdAdmision] ASC)
);

