CREATE TABLE [dbo].[aca_MatriculaAsistencia] (
    [IdEmpresa]             INT           NOT NULL,
    [IdMatricula]           NUMERIC (18)  NOT NULL,
    [FInjustificadaP1]      INT           NULL,
    [FJustificadaP1]        INT           NULL,
    [AtrasosP1]             INT           NULL,
    [FInjustificadaP2]      INT           NULL,
    [FJustificadaP2]        INT           NULL,
    [AtrasosP2]             INT           NULL,
    [FInjustificadaP3]      INT           NULL,
    [FJustificadaP3]        INT           NULL,
    [AtrasosP3]             INT           NULL,
    [FInjustificadaP4]      INT           NULL,
    [FJustificadaP4]        INT           NULL,
    [AtrasosP4]             INT           NULL,
    [FInjustificadaP5]      INT           NULL,
    [FJustificadaP5]        INT           NULL,
    [AtrasosP5]             INT           NULL,
    [FInjustificadaP6]      INT           NULL,
    [FJustificadaP6]        INT           NULL,
    [AtrasosP6]             INT           NULL,
    [IdUsuarioCreacion]     VARCHAR (200) NULL,
    [FechaCreacion]         DATETIME      NULL,
    [IdUsuarioModificacion] VARCHAR (200) NULL,
    [FechaModificacion]     DATETIME      NULL,
    CONSTRAINT [PK_aca_MatriculaAsistencia] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdMatricula] ASC),
    CONSTRAINT [FK_aca_MatriculaAsistencia_aca_Matricula] FOREIGN KEY ([IdEmpresa], [IdMatricula]) REFERENCES [dbo].[aca_Matricula] ([IdEmpresa], [IdMatricula])
);

