//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAf_Activo_fijo
    {
        public int IdEmpresa { get; set; }
        public int IdActivoFijo { get; set; }
        public string Af_Nombre { get; set; }
        public string Estado { get; set; }
        public string EstadoProceso { get; set; }
        public string NomCategoria { get; set; }
        public string NomTipo { get; set; }
        public string NomArea { get; set; }
        public string NomDepartamento { get; set; }
        public string NomEncargado { get; set; }
        public string NomCustodio { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public int Cantidad { get; set; }
        public string Estado_Proceso { get; set; }
    }
}
