//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_orden_giro_LiquidacionDeCompras
    {
        public int IdEmpresa { get; set; }
        public int IdTipoCbte_Ogiro { get; set; }
        public decimal IdCbteCble_Ogiro { get; set; }
        public System.DateTime co_FechaFactura { get; set; }
        public string co_factura { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string Num_Autorizacion { get; set; }
        public string Codigo { get; set; }
        public string Estado { get; set; }
        public double co_total { get; set; }
        public string co_observacion { get; set; }
        public int IdSucursal { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string EstadoCancelacion { get; set; }
    }
}
