//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_notaCreDeb
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdNota { get; set; }
        public string CreDeb { get; set; }
        public string NumNota_Impresa { get; set; }
        public System.DateTime no_fecha { get; set; }
        public string Nombres { get; set; }
        public Nullable<double> sc_subtotal { get; set; }
        public Nullable<double> sc_iva { get; set; }
        public Nullable<double> sc_total { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> IdAlumno { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string sc_observacion { get; set; }
        public string IdUsuario { get; set; }
        public string No_Descripcion { get; set; }
        public string NumAutorizacion { get; set; }
        public string NaturalezaNota { get; set; }
        public Nullable<System.DateTime> Fecha_Autorizacion { get; set; }
    }
}
