//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_EmpleadoAnticipoBeneficio
    {
        public int IdEmpresa { get; set; }
        public decimal IdAnticipo { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public double Valor { get; set; }
        public string ru_descripcion { get; set; }
        public string pe_nombreCompleto { get; set; }
        public bool Estado { get; set; }
    }
}
